<template>
  <div id="app">
    <template>
      <div class="menu">
        <el-row>
          <el-col :span="24">
              <el-col :span="3">
                <el-input v-model="datelist.name" suffix-icon="el-icon-edit" placeholder="运动员姓名"></el-input>
              </el-col>
              <el-col :span="4">
                <el-date-picker
                  v-model="datelist.start"
                  type="date"
                  style="width: 100%"
                  placeholder="选择日期"
                  format="yyyy 年 MM 月 dd 日"
                  value-format="yyyy-MM-dd">
                </el-date-picker>
              </el-col>
            <el-col :span="4">
              <el-date-picker
                v-model="datelist.end"
                type="date"
                style="width: 100%"
                placeholder="选择日期"
                format="yyyy 年 MM 月 dd 日"
                value-format="yyyy-MM-dd">
              </el-date-picker>
            </el-col>
            <el-col :span="2">
              <el-button type="primary" icon="el-icon-search" @click="selectName">搜索</el-button>
            </el-col>
          </el-col>
        </el-row>
      </div>
      <el-table
        :data="tableData"
        height="550"
        border
        style="width: 100%">
        <el-table-column
          fixed
          prop="displayname"
          label="运动员名称"
          width="120">
        </el-table-column>
        <el-table-column
          fixed
          prop="start"
          label="开始时间"
          width="170">
        </el-table-column>
        <el-table-column
          fixed
          prop="end"
          label="结束时间"
          width="170">
        </el-table-column>
        <el-table-column
          prop="distance_total"
          label="总距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_zonal"
          label="距离分区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z1"
          label="速度1区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z1_ab"
          label="速度1区距离（绝对值"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z2"
          label="速度2区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z2_ab"
          label="速度2区距离（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z3"
          label="速度3区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z3_ab"
          label="速度3区距离（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z4"
          label="速度4区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z4_ab"
          label="速度4区距离（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z5"
          label="速度5区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z5_ab"
          label="速度5区距离（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z6"
          label="速度6区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distance_z6_ab"
          label="速度6区距离（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z1"
          label="速度1区时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z1_ab"
          label="速度1区时间（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z2"
          label="速度2区时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z2_ab"
          label="速度2区时间（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z3"
          label="速度3区时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z3_ab"
          label="速度3区时间（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z4"
          label="速度4区时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z4_ab"
          label="速度4区时间（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z5"
          label="速度5区时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z5_ab"
          label="速度5区时间（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z6"
          label="速度6区时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="time_z6_ab"
          label="速度6区时间（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="average_speed"
          label="平均速度"
          width="120">
        </el-table-column>
        <el-table-column
          prop="max_speed"
          label="最大速度"
          width="120">
        </el-table-column>
        <el-table-column
          prop="speed_exertion"
          label="速度输出"
          width="120">
        </el-table-column>
        <el-table-column
          prop="speedexertion_z1"
          label="速度1区输出"
          width="120">
        </el-table-column>
        <el-table-column
          prop="speedexertion_z2"
          label="速度2区输出"
          width="120">
        </el-table-column>
        <el-table-column
          prop="speedexertion_z3"
          label="速度3区输出"
          width="120">
        </el-table-column>
        <el-table-column
          prop="speedexertion_z4"
          label="速度4区输出"
          width="120">
        </el-table-column>
        <el-table-column
          prop="speedexertion_z5"
          label="速度5区输出"
          width="120">
        </el-table-column>
        <el-table-column
          prop="speedexertion_z6"
          label="速度6区输出"
          width="120">
        </el-table-column>
        <el-table-column
          prop="bodyload"
          label="身体负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="bodyload_z1"
          label="负荷1区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="bodyload_z2"
          label="负荷2区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="bodyload_z3"
          label="负荷3区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="bodyload_z4"
          label="负荷4区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="bodyload_z5"
          label="负荷5区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="bodyload_z6"
          label="负荷6区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="hr_exertion"
          label="心率强度"
          width="120">
        </el-table-column>
        <el-table-column
          prop="timeheartrate_z1"
          label="心率强度1区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="timeheartrate_z2"
          label="心率强度2区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="timeheartrate_z3"
          label="心率强度3区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="timeheartrate_z4"
          label="心率强度4区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="timeheartrate_z5"
          label="心率强度5区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="timeheartrate_z6"
          label="心率强度6区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="impacts"
          label="冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="impacts_z1"
          label="冲击1区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="impacts_z2"
          label="冲击2区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="impacts_z3"
          label="冲击3区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="impacts_z4"
          label="冲击4区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="impacts_z5"
          label="冲击5区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="impacts_z6"
          label="冲击6区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprints"
          label="冲刺"
          width="120">
        </el-table-column>
        <el-table-column
          prop="explosivepowerefforts"
          label="爆发次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="accelerations"
          label="加速次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="decelerations"
          label="减速次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="updated"
          label="更新次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="totalleftsteps"
          label="左脚步数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="totalrightsteps"
          label="右脚步数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="leftverticalimpact"
          label="左脚垂直冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="leftlateralimpact"
          label="左脚左侧冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="leftantpostimpact"
          label="左脚后侧冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="leftmagimpact"
          label="左脚前侧冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="leftaveragevertimpact"
          label="左脚平均冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="rightverticalimpact"
          label="右脚垂直冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="rightlateralimpact"
          label="右脚左侧冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="rightantpostimpact"
          label="右脚后侧冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="rightmagimpact"
          label="右脚前侧冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="rightaveragevertimpact"
          label="右脚平均冲击"
          width="120">
        </el-table-column>
        <el-table-column
          prop="stepbalance"
          label="步态平衡"
          width="120">
        </el-table-column>
        <el-table-column
          prop="accelerations_z1"
          label="加速1区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="accelerations_z2"
          label="加速2区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="accelerations_z3"
          label="加速3区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="accelerations_z4"
          label="加速4区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="accelerations_z5"
          label="加速5区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="accelerations_z6"
          label="加速6区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="decelerations_z1"
          label="减速1区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="decelerations_z2"
          label="减速2区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="decelerations_z3"
          label="减速3区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="decelerations_z4"
          label="减速4区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="decelerations_z5"
          label="减速5区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="decelerations_z6"
          label="减速6区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="totalmetabolicpower"
          label="总代谢能力"
          width="120">
        </el-table-column>
        <el-table-column
          prop="averagemetabolicpower"
          label="平均代谢能力"
          width="120">
        </el-table-column>
        <el-table-column
          prop="totaltime"
          label="总时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="distancepermin"
          label="每分钟距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="highmetabolicpowerdistance"
          label="高代谢功率距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicdistance"
          label="代谢距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="maxheartrate"
          label="最大心率"
          width="120">
        </el-table-column>
        <el-table-column
          prop="dynamicloadmag"
          label="前侧动态负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="dynamicloadvert"
          label="平局动态负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="dynamicloadlat"
          label="左侧动态负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="dynamicloadant"
          label="后侧动态负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="dynamicloadslow"
          label="缓慢动态负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="averageheartrate"
          label="平均心率"
          width="120">
        </el-table-column>
        <el-table-column
          prop="highmetabolicpowertime"
          label="高强度负荷时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone1distance"
          label="1区强度负荷距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone2distance"
          label="2区强度负荷距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone3distance"
          label="3区强度负荷距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone4distance"
          label="4区强度负荷距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone5distance"
          label="5区强度负荷距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone6distance"
          label="6区强度负荷距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone1time"
          label="1区强度负荷时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone2time"
          label="2区强度负荷时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone3time"
          label="3区强度负荷时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone4time"
          label="4区强度负荷时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone5time"
          label="5区强度负荷时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="metabolicpowerzone6time"
          label="6区强度负荷时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="collisionsnumber"
          label="碰撞次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="collisionsload"
          label="碰撞负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="scrumsnumber"
          label="冲击次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="scrumsload"
          label="冲击负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="tacklesnumber"
          label="抢断次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="carrysnumber"
          label="带球次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="rucksnumber"
          label="过人次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="highintensityburstnumber"
          label="高强度爆发次数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="highintensityburstduration"
          label="高强度爆发时间"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintdistance"
          label="冲刺距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="totaldecelloading"
          label="总减速负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries1ab"
          label="冲刺1区（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries1rel"
          label="冲刺1区（相对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries2ab"
          label="冲刺2区（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries2rel"
          label="冲刺2区（相对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries3ab"
          label="冲刺3区（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries3rel"
          label="冲刺3区（相对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries4ab"
          label="冲刺4区（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries4rel"
          label="冲刺4区（相对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries5ab"
          label="冲刺5区（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries5rel"
          label="冲刺5区（相对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries6ab"
          label="冲刺6区（绝对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="sprintentries6rel"
          label="冲刺6区（相对值）"
          width="120">
        </el-table-column>
        <el-table-column
          prop="acceltotaldistancez1"
          label="加速1区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="acceltotaldistancez2"
          label="加速2区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="acceltotaldistancez3"
          label="加速3区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="acceltotaldistancez4"
          label="加速4区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="acceltotaldistancez5"
          label="加速5区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="acceltotaldistancez6"
          label="加速6区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="deceltotaldistancez1"
          label="减速1区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="deceltotaldistancez2"
          label="减速2区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="deceltotaldistancez3"
          label="减速3区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="deceltotaldistancez4"
          label="减速4区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="deceltotaldistancez5"
          label="减速5区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="deceltotaldistancez6"
          label="减速6区距离"
          width="120">
        </el-table-column>
        <el-table-column
          prop="accelerationimpulse"
          label="加速度脉冲"
          width="120">
        </el-table-column>
        <el-table-column
          prop="externalwork"
          label="外部工作"
          width="120">
        </el-table-column>
        <el-table-column
          prop="heartrateload"
          label="心率负荷"
          width="120">
        </el-table-column>
        <el-table-column
          prop="acutechronicratio"
          label="快慢比率"
          width="120">
        </el-table-column>
        <el-table-column
          prop="totaldives"
          label="总跳跃数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="totalleftdives"
          label="左侧跳跃数"
          width="120">
        </el-table-column>
        <el-table-column
          prop="totalrightdives"
          label="右侧跳跃数"
          width="120">
        </el-table-column>
      </el-table>
    </template>
    <!--paging-->
    <div class="block">
      <el-pagination
        class="classpager"
        @current-change="handleCurrentChange"
        background
        :page-size="100"
        :current-page.sync="currentPage1"
        layout="total,prev, pager, next"
        :total="pageSizi">
      </el-pagination>
    </div>
  </div>
</template>
<script>
  import fetch from "@/assets/js/fetch.js";
  import qs from "qs";
  export default {
  name: "productDataList",
  data:function () {
      return{
        currentPage1:1,
        //搜索状态（1时间周期）（2运动员姓名）
        state:true,
        //时间周期
        datelist:{
          //运动员名称
          initpage:"",
          name:"",
          start:"",
          end:""
        },
        pageSizi:null,
        tableData:[]
   }
  },
  //initfunction
  created(){
    this.getdata()
  },
  //计算属性
  computed:{
  },
  //funcation
  methods:{
    //selectplayer
    selectName() {
      this.currentPage1=1
      this.datelist.initpage="1"
      fetch.get("/SC/selectPlayerCountBynameOrTime",{params:this.datelist}).then(res=>{
        console.log(this.currentPage1);
        this.pageSizi=res.data.allsize;
        this.tableData=res.data.data;
        this.state=false
      })
    },
    getdata(){
      fetch.get("/SC/selectPlayerCount",{
        params:{
          initpage:1,
        }
      }).then(res=>{
        this.tableData=res.data.data;
        this.pageSizi=res.data.allsize
      }).catch(error=>{
        console.log("请求失败")
      })
    },
    //pageSizievent
    handleCurrentChange(val) {
      console.log(val)
      if(this.state){
        fetch.get("/SC/selectPlayerCount",{
          params: {
            initpage:val,
          }
        }).then(res=>{
          this.tableData=res.data.data;
        })
      }else  {
          fetch.get("/SC/selectPlayerCountBynameOrTime",{
            params:{
              initpage:val,
              name:this.datelist.name,
              start:this.datelist.start,
              end:this.datelist.end
            }
          })
            .then(res=>{
            console.log(this.currentPage1);
            this.pageSizi=res.data.allsize;
            this.tableData=res.data.data;
            this.state=false
          })
      }
    }
  }
};
</script>
<style scoped lang="stylus">
  .classpager{
    border 1px solid white;
    background-color white
  }
/*.menu{*/
  /*margin-top: 5px;*/
  /*width: 80%;*/
  /*margin-left: 10%;*/
  /*user-select: none;*/
/*}*/
</style>
